# Generated by Django 5.0.1 on 2024-01-03 18:37

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_alter_note_shared_with"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                blank=True, null=True
            ),
        ),
    ]
