# Generated by Django 5.0.1 on 2024-01-03 19:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_note_search_vector"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="shared_with",
            field=models.ManyToManyField(
                blank=True, related_name="shared_notes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
